export const reelsVidinfo = [
  {
    path: "/ReelsVid/Vid-1.mp4",
    user: "Sunil-Sexy",
    description: "Aja hami gako yah ghumna",
    likes: 49,
    saves: 14,
    comments: [
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
    ],
    shares: 5,
    isLiked: false,
    isSaved: false,
  },
  {
    path: "/ReelsVid/Vid-2.mp4",
    user: "Bipin",
    description: "Aja hami gako yah ghumna",
    likes: 29,
    saves: 21,
    comments: [
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
    ],
    shares: 12,
    isLiked: true,
    isSaved: false,

  },
  {
    path: "/ReelsVid/Vid-3.mp4",
    user: "Alson-Hoty",
    description: "Aja hami gako yah ghumna",
    likes: 89,
    saves: 14,
    comments: [
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
    ],
    shares: 13,
    isLiked: false,
    isSaved: false,

  },
  {
    path: "/ReelsVid/Vid-1.mp4",
    user: "Utsab-don",
    description: "Aja hami gako yah ghumna",
    likes: 28,
    saves: 9,
    comments: [
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
    ],
    shares: 3,
    isLiked: false,
    isSaved: true,
  },
]