export const reelsVidinfo = [
  {
    path: "/ReelsVid/Vid-1.mp4",
    user: "Sunil-Sexy",
    description: "Aja hami gako yah ghumna",
    likes: 289,
    saves: 24,
    comments: [
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
    ],
    shares: 21,
    isLiked: false,
    isSaved: true,
  },
  {
    path: "/ReelsVid/Vid-2.mp4",
    user: "Bipin",
    description: "Aja hami gako yah ghumna",
    likes: 289,
    saves: 24,
    comments: [
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
    ],
    shares: 21,
    isLiked: true,
    isSaved: true,

  },
  {
    path: "/ReelsVid/Vid-3.mp4",
    user: "Alson-Hoty",
    description: "Aja hami gako yah ghumna",
    likes: 289,
    saves: 24,
    comments: [
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
    ],
    shares: 21,
    isLiked: true,
    isSaved: true,

  },
  {
    path: "/ReelsVid/Vid-1.mp4",
    user: "Utsab-don",
    description: "Aja hami gako yah ghumna",
    likes: 289,
    saves: 24,
    comments: [
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
      { comment: "djljdljs", like: 34, user: "alson" },
    ],
    shares: 21,
    isLiked: true,
    isSaved: true,

  },
]